много всего по сборке обновление generator'a + убран SkipMulligan

diff --git a/.github/workflows/AndroidMixMod.yml b/.github/workflows/AndroidMixMod.yml
--- a/.github/workflows/AndroidMixMod.yml
+++ b/.github/workflows/AndroidMixMod.yml
@@ -2,56 +2,83 @@ name: AndroidMixMod workflow
 
 on:
   workflow_dispatch:
-
+  push:
+    branches:
+      - main
+      - 'releases/**'
+      
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Clone repository
+      - name: Checkout code
         uses: actions/checkout@v3
-      - name: set up JDK 11
+
+      - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
           java-version: '11'
           distribution: 'temurin'
           cache: gradle
+
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
         with:
           gradle-version: 7.5.1
+
+      - name: Cache NDK
+        uses: actions/cache@v3
+        with:
+          path: ~/.android/ndk
+          key: ndk-${{ runner.os }}-r26
+          restore-keys: |
+            ndk-${{ runner.os }}-
+
+      - name: Cache Android SDK
+        uses: actions/cache@v3
+        with:
+          path: ~/.android
+          key: android-sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/build.gradle.kts') }}
+          restore-keys: |
+            android-sdk-${{ runner.os }}-
+
       - name: Setup Android SDK
         uses: android-actions/setup-android@v2
+
       - name: Setup NDK
         uses: nttld/setup-ndk@v1
         id: setup-ndk
         with:
           ndk-version: r26
           local-cache: true
+
+      - name: Cache .NET packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.nuget/packages
+          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/*.fsproj') }}
+          restore-keys: |
+            nuget-${{ runner.os }}-
+
       - name: Setup .NET 6.0
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 6.0.x
-      - name: Download hearthstone apk
+      - name: Cache Hearthstone APK
+        uses: actions/cache@v3
+        with:
+          path: ../downloads/hs.apk
+          key: hs-apk-${{ secrets.VERSION }}
+          restore-keys: |
+            hs-apk-
+
+      - name: Download Hearthstone APK
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           repo_dir=$(pwd)
-          mkdir ../downloads/
+          mkdir -p ../downloads/
           cd ../downloads/
-          curl '${{ secrets.APK_URL }}' \
-            -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
-            -H 'Accept-Language: ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7,vi;q=0.6' \
-            -H 'Cache-Control: no-cache' \
-            -H 'Connection: keep-alive' \
-            -H 'Pragma: no-cache' \
-            -H 'Sec-Fetch-Dest: document' \
-            -H 'Sec-Fetch-Mode: navigate' \
-            -H 'Sec-Fetch-Site: none' \
-            -H 'Sec-Fetch-User: ?1' \
-            -H 'Upgrade-Insecure-Requests: 1' \
-            -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
-            -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
-            -H 'sec-ch-ua-mobile: ?0' \
-            -H 'sec-ch-ua-platform: "macOS"' \
-            -o hs.apk
+          curl '${{ secrets.APK_URL }}' -o hs.apk
           old_apk_name="hs.apk"
           apk_name="hs.apk"
           mixmod_apk_name="HearthstoneMixMod_${{ secrets.VERSION }}.apk"
@@ -61,30 +88,84 @@ jobs:
           echo "apk_folder_name=${apk_folder_name}" >> $GITHUB_ENV
           echo "apk_version=${apk_folder_name#*_}" >> $GITHUB_ENV
           cd ${repo_dir}
+
+      - name: Cache Apktool
+        uses: actions/cache@v3
+        with:
+          path: ../downloads/apktool.jar
+          key: apktool-v2.9.3
       - name: Download Apktool
-        run: wget https://github.com/iBotPeaches/Apktool/releases/download/v2.8.1/apktool_2.8.1.jar -O ../downloads/apktool.jar
+        if: steps.cache.outputs.cache-hit != 'true'  # Скачать, только если кэша нет
+        run: wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O ../downloads/apktool.jar
+
       - name: Decompile hearthstone apk
         run: |
           repo_dir=$(pwd)
           cd ../downloads/
           java -jar apktool.jar d ${{ env.apk_name }} -o ${{ env.apk_folder_name }}
           cd ${repo_dir}
-      - name: Modify hearthstone apk
+
+      - name: Set variables
+        id: vars
         run: |
-          repo_dir=$(pwd)
-          cd ../downloads/${{ env.apk_folder_name }}/
-          git apply ${repo_dir}/0001-AndroidMixMod.patch
-          cd ${repo_dir}
+          echo "repo_dir=$(pwd)" >> $GITHUB_ENV
+          echo "apk_folder_path=../downloads/${{ env.apk_folder_name }}" >> $GITHUB_ENV
+      
+      - name: Save original files before patch
+        run: |
+          mkdir -p $GITHUB_WORKSPACE/original_files
+          cd ../downloads/${{ env.apk_folder_name }}
+          cp --parents \
+            AndroidManifest.xml \
+            smali/com/blizzard/mobile/auth/internal/packagevalidator/BasePackageValidator.smali \
+            smali/com/blizzard/wtcg/hearthstone/FileUtils.smali \
+            smali/com/blizzard/wtcg/hearthstone/HearthstoneActivity.smali \
+            smali/com/blizzard/wtcg/hearthstone/LoadingScreen.smali \
+            apktool.yml \
+            $GITHUB_WORKSPACE/original_files
+          cd -
+
+
+      - name: Apply patch and save conflicts
+        run: |
+          cd ${{ env.apk_folder_path }}
+          git apply --reject ${{ env.repo_dir }}/0003-AndroidMixMod.patch || true
+          
+      - name: Collect conflict files
+        run: |
+          mkdir -p ./conflicts
+          find . -name "*.rej" -o -name "AndroidManifest.xml" -o -name "LoadingScreen.smali" | \
+          xargs -I {} cp --parents {} ./conflicts
+
+      - name: Upload conflict files as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: patch-conflicts
+          path: ${{ env.repo_dir }}/conflicts
+          
+      - name: Cache Il2CppDumper
+        uses: actions/cache@v3
+        with:
+          path: ../downloads/Il2CppDumper
+          key: il2cppdumper-v6.7.46
       - name: Download Il2CppDumper
+        if: steps.cache.outputs.cache-hit != 'true'  # Скачать, только если кэша нет
         run: |
           repo_dir=$(pwd)
           cd ../downloads/
-          wget $(jq -r '.assets[] | select(.name | contains("net6") and (contains("win") | not)) | .browser_download_url' <<< $(curl --silent https://api.github.com/repos/Perfare/Il2CppDumper/releases/latest)) -O ./Il2CppDumper.zip
+          wget https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.46/Il2CppDumper-net6-v6.7.46.zip -O ./Il2CppDumper.zip
           unzip Il2CppDumper.zip -d Il2CppDumper
           sed -i "s/\"GenerateDummyDll\": true/\"GenerateDummyDll\": false/" ./Il2CppDumper/config.json
           sed -i "s/\"RequireAnyKey\": true/\"RequireAnyKey\": false/" ./Il2CppDumper/config.json
           cd ${repo_dir}
+
+      - name: Cache Generator
+        uses: actions/cache@v3
+        with:
+          path: ../downloads/Generator
+          key: generator-latest
       - name: Download Generator
+        if: steps.cache.outputs.cache-hit != 'true'  # Скачать, только если кэша нет
         run: |
           repo_dir=$(pwd)
           cd ../downloads/
@@ -92,6 +173,18 @@ jobs:
           unzip Generator.zip -d Generator
           chmod +x ./Generator/Generator
           cd ${repo_dir}
+
+# На случай если нужен будет лог
+#  echo "Full path to arm64-v8a:"
+#  realpath ./arm64-v8a
+#  echo "Contents of ./arm64-v8a:"
+#  ls -la ./arm64-v8a
+#  echo "Contents of downloads directory:"
+#  ls -la ../downloads
+#  cp ./arm64-v8a/script.json ${repo_dir}/script.json
+#  echo "Contents of ./hs:"
+#  ls -la ./${{ env.apk_folder_name }}/lib/
+
       - name: Dump with Il2CppDumper
         run: |
           repo_dir=$(pwd)
@@ -100,9 +193,62 @@ jobs:
           dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./arm64-v8a/
           mkdir armeabi-v7a
           dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./armeabi-v7a/
-          cp ./arm64-v8a/il2cpp.h ${repo_dir}/app/src/main/jni/Includes/
-          sed -i "s/std\(in\|out\|err\)/_std\1/g" ${repo_dir}/app/src/main/jni/Includes/il2cpp.h
+
+          libil2cpp_path="./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so"
+              metadata_path="./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat"
+              
+              if [ -f "$libil2cpp_path" ]; then
+                echo "libil2cpp.so exists."
+                ls -l "$libil2cpp_path"
+              else
+                echo "ERROR: libil2cpp.so does not exist at $libil2cpp_path"
+              fi
+              
+              if [ -f "$metadata_path" ]; then
+                echo "global-metadata.dat exists."
+                ls -l "$metadata_path"
+              else
+                echo "ERROR: global-metadata.dat does not exist at $metadata_path"
+              fi
+              
+              if [ ! -f "$libil2cpp_path" ] || [ ! -f "$metadata_path" ]; then
+                echo "One or both required files are missing. Exiting."
+                exit 1
+              fi
+          
+          # cp ./arm64-v8a/il2cpp.h ${repo_dir}/app/src/main/jni/Includes/
+          # sed -i "s/std\(in\|out\|err\)/_std\1/g" ${repo_dir}/app/src/main/jni/Includes/il2cpp.h
+          dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./arm64-v8a/ --no-cpp
+          file ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so
+          strings ./${{ env.apk_folder_name }}/lib/arm64-v8a/libunity.so | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+f[0-9]\+"
           cd ${repo_dir}
+
+      - name: Copy script.json
+        run: |
+          repo_dir=$(pwd)
+          cd ../downloads/
+          cp ./arm64-v8a/script.json ${{ github.workspace }}/script.json
+          cp ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ${{ github.workspace }}/libil2cpp.so
+          if [ -f "${{ github.workspace }}/script.json" ]; then
+            echo "script.json found."
+          else
+            echo "script.json not found."
+          fi
+
+      - name: Save script.json to artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: script-json
+          path: ${{ github.workspace }}/script.json
+
+      - name: Save libil2cpp to artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: libil2cpp
+          path: ${{ github.workspace }}/libil2cpp.so
+
       - name: Generate offsets
         run: |
           repo_dir=$(pwd)
@@ -110,7 +256,7 @@ jobs:
           search_str="androidRenderOutsideSafeArea"
           echo "#ifdef __aarch64__" > ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           ./Generator/Generator ${repo_dir}/OffsetsTemplate.json ./arm64-v8a/script.json ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ARM64 >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          offset=$(grep -oba -m1 -o ${search_str} ./${{ env.apk_folder_name }}/lib/arm64-v8a/libunity.so)
+          offset=$(grep -oba -m1 -o ${search_str} ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libunity.so)
           printf "#define Unity_AndroidRenderOutsideSafeArea_Offset \"0x%X\"\n" $((${offset%:${search_str}} + ${#search_str} - 1)) >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           echo -e "#else\n" >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           ./Generator/Generator ${repo_dir}/OffsetsTemplate.json ./armeabi-v7a/script.json ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libil2cpp.so ARM >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
@@ -118,9 +264,7 @@ jobs:
           printf "#define Unity_AndroidRenderOutsideSafeArea_Offset \"0x%X\"\n" $((${offset%:${search_str}} + ${#search_str} - 1)) >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           echo "#endif" >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           cd ${repo_dir}
-      # - name: Commit changes
-      #   id: git_auto_commit
-      #   uses: stefanzweifel/git-auto-commit-action@v4
+
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Build with Gradle
@@ -167,5 +311,5 @@ jobs:
       - uses: "ncipollo/release-action@v1"
         with:
           tag: "${{ secrets.VERSION }}"
-          name: "AndroidMixMod"
+          name: "v. ${{ secrets.VERSION }}"
           artifacts: "../Release/signed/${{ env.mixmod_apk_name }}"
