win config

diff --git a/.github/workflows/AndroidMixMod.yml b/.github/workflows/AndroidMixMod.yml
--- a/.github/workflows/AndroidMixMod.yml
+++ b/.github/workflows/AndroidMixMod.yml
@@ -22,17 +22,9 @@ jobs:
           cache: gradle
 
       - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/actions/setup-gradle@v4
         with:
-          gradle-version: 7.5.1
-
-      - name: Cache NDK
-        uses: actions/cache@v3
-        with:
-          path: ~/.android/ndk
-          key: ndk-${{ runner.os }}-r26
-          restore-keys: |
-            ndk-${{ runner.os }}-
+          gradle-version: 8.10
 
       - name: Cache Android SDK
         uses: actions/cache@v3
@@ -43,14 +35,10 @@ jobs:
             android-sdk-${{ runner.os }}-
 
       - name: Setup Android SDK
-        uses: android-actions/setup-android@v2
-
-      - name: Setup NDK
-        uses: nttld/setup-ndk@v1
-        id: setup-ndk
+        uses: android-actions/setup-android@v3
         with:
-          ndk-version: r26
-          local-cache: true
+          cmdline-tools-version: 12266719
+          packages: 'platform-tools platforms;android-31 build-tools;30.0.3 ndk;26.3.11579264'
 
       - name: Cache .NET packages
         uses: actions/cache@v3
@@ -64,21 +52,29 @@ jobs:
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 6.0.x
+
       - name: Cache Hearthstone APK
         uses: actions/cache@v3
+        id: apk-cache
         with:
-          path: ../downloads/hs.apk
-          key: hs-apk-${{ secrets.VERSION }}
+          path: ${{ github.workspace }}/downloads/hs.apk
+          key: hs-apk
           restore-keys: |
             hs-apk-
 
       - name: Download Hearthstone APK
-        if: steps.cache.outputs.cache-hit != 'true'
+        if: steps.apk-cache.outputs.cache-hit != 'true'
+        run: |
+          repo_dir=$(pwd)
+          mkdir -p ${{ github.workspace }}/downloads/
+          curl -L "${{ secrets.APK_URL }}" -o "${{ github.workspace }}/downloads/hs.apk"
+
+      - name: Process Hearthstone APK
         run: |
           repo_dir=$(pwd)
           mkdir -p ../downloads/
           cd ../downloads/
-          curl '${{ secrets.APK_URL }}' -o hs.apk
+          cp ${{ github.workspace }}/downloads/hs.apk hs.apk
           old_apk_name="hs.apk"
           apk_name="hs.apk"
           mixmod_apk_name="HearthstoneMixMod_${{ secrets.VERSION }}.apk"
@@ -91,12 +87,18 @@ jobs:
 
       - name: Cache Apktool
         uses: actions/cache@v3
+        id: apktool-cache
         with:
           path: ../downloads/apktool.jar
-          key: apktool-v2.9.3
+          key: apktool-v2.9.3  # Жестко фиксируем версию в ключе
+          restore-keys: |
+            apktool-
+
       - name: Download Apktool
-        if: steps.cache.outputs.cache-hit != 'true'  # Скачать, только если кэша нет
-        run: wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O ../downloads/apktool.jar
+        if: steps.apktool-cache.outputs.cache-hit != 'true'
+        run: |
+          mkdir -p ../downloads/
+          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O ../downloads/apktool.jar
 
       - name: Decompile hearthstone apk
         run: |
@@ -110,7 +112,7 @@ jobs:
         run: |
           echo "repo_dir=$(pwd)" >> $GITHUB_ENV
           echo "apk_folder_path=../downloads/${{ env.apk_folder_name }}" >> $GITHUB_ENV
-      
+
       - name: Save original files before patch
         run: |
           mkdir -p $GITHUB_WORKSPACE/original_files
@@ -129,20 +131,20 @@ jobs:
       - name: Apply patch and save conflicts
         run: |
           cd ${{ env.apk_folder_path }}
-          git apply --reject ${{ env.repo_dir }}/0003-AndroidMixMod.patch || true
-          
-      - name: Collect conflict files
-        run: |
-          mkdir -p ./conflicts
-          find . -name "*.rej" -o -name "AndroidManifest.xml" -o -name "LoadingScreen.smali" | \
-          xargs -I {} cp --parents {} ./conflicts
+          git apply --reject ${{ env.repo_dir }}/0004-AndroidMixMod.patch || true
+#
+#      - name: Collect conflict files
+#        run: |
+#          mkdir -p ./conflicts
+#          find . -name "*.rej" -o -name "AndroidManifest.xml" -o -name "LoadingScreen.smali" | \
+#          xargs -I {} cp --parents {} ./conflicts
+#
+#      - name: Upload conflict files as artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: patch-conflicts
+#          path: ${{ env.repo_dir }}/conflicts
 
-      - name: Upload conflict files as artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: patch-conflicts
-          path: ${{ env.repo_dir }}/conflicts
-          
       - name: Cache Il2CppDumper
         uses: actions/cache@v3
         with:
@@ -191,86 +193,58 @@ jobs:
           cd ../downloads/
           mkdir arm64-v8a
           dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./arm64-v8a/
-          mkdir armeabi-v7a
-          dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./armeabi-v7a/
 
-          libil2cpp_path="./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so"
-              metadata_path="./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat"
-              
-              if [ -f "$libil2cpp_path" ]; then
-                echo "libil2cpp.so exists."
-                ls -l "$libil2cpp_path"
-              else
-                echo "ERROR: libil2cpp.so does not exist at $libil2cpp_path"
-              fi
-              
-              if [ -f "$metadata_path" ]; then
-                echo "global-metadata.dat exists."
-                ls -l "$metadata_path"
-              else
-                echo "ERROR: global-metadata.dat does not exist at $metadata_path"
-              fi
-              
-              if [ ! -f "$libil2cpp_path" ] || [ ! -f "$metadata_path" ]; then
-                echo "One or both required files are missing. Exiting."
-                exit 1
-              fi
-          
           # cp ./arm64-v8a/il2cpp.h ${repo_dir}/app/src/main/jni/Includes/
           # sed -i "s/std\(in\|out\|err\)/_std\1/g" ${repo_dir}/app/src/main/jni/Includes/il2cpp.h
           dotnet ./Il2CppDumper/Il2CppDumper.dll ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ./${{ env.apk_folder_name }}/assets/bin/Data/Managed/Metadata/global-metadata.dat ./arm64-v8a/ --no-cpp
           file ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so
           strings ./${{ env.apk_folder_name }}/lib/arm64-v8a/libunity.so | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+f[0-9]\+"
           cd ${repo_dir}
-
-      - name: Copy script.json
-        run: |
-          repo_dir=$(pwd)
-          cd ../downloads/
-          cp ./arm64-v8a/script.json ${{ github.workspace }}/script.json
-          cp ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ${{ github.workspace }}/libil2cpp.so
-          if [ -f "${{ github.workspace }}/script.json" ]; then
-            echo "script.json found."
-          else
-            echo "script.json not found."
-          fi
-
-      - name: Save script.json to artifacts
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: script-json
-          path: ${{ github.workspace }}/script.json
-
-      - name: Save libil2cpp to artifacts
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: libil2cpp
-          path: ${{ github.workspace }}/libil2cpp.so
+#
+#      - name: Copy script.json
+#        run: |
+#          repo_dir=$(pwd)
+#          cd ../downloads/
+#          cp ./arm64-v8a/script.json ${{ github.workspace }}/script.json
+#          cp ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ${{ github.workspace }}/libil2cpp.so
+#          if [ -f "${{ github.workspace }}/script.json" ]; then
+#            echo "script.json found."
+#          else
+#            echo "script.json not found."
+#          fi
+#
+#      - name: Save script.json to artifacts
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: script-json
+#          path: ${{ github.workspace }}/script.json
+#
+#      - name: Save libil2cpp to artifacts
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: libil2cpp
+#          path: ${{ github.workspace }}/libil2cpp.so
 
       - name: Generate offsets
         run: |
           repo_dir=$(pwd)
           cd ../downloads/
           search_str="androidRenderOutsideSafeArea"
-          echo "#ifdef __aarch64__" > ${repo_dir}/app/src/main/jni/Includes/Offsets.h
           ./Generator/Generator ${repo_dir}/OffsetsTemplate.json ./arm64-v8a/script.json ./${{ env.apk_folder_name }}/lib/arm64-v8a/libil2cpp.so ARM64 >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          offset=$(grep -oba -m1 -o ${search_str} ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libunity.so)
-          printf "#define Unity_AndroidRenderOutsideSafeArea_Offset \"0x%X\"\n" $((${offset%:${search_str}} + ${#search_str} - 1)) >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          echo -e "#else\n" >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          ./Generator/Generator ${repo_dir}/OffsetsTemplate.json ./armeabi-v7a/script.json ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libil2cpp.so ARM >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          offset=$(grep -oba -m1 -o ${search_str} ./${{ env.apk_folder_name }}/lib/armeabi-v7a/libunity.so)
-          printf "#define Unity_AndroidRenderOutsideSafeArea_Offset \"0x%X\"\n" $((${offset%:${search_str}} + ${#search_str} - 1)) >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
-          echo "#endif" >> ${repo_dir}/app/src/main/jni/Includes/Offsets.h
+          
           cd ${repo_dir}
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
+
       - name: Build with Gradle
-        run: ./gradlew build
-        env:
-          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
+        run: |
+          ./gradlew clean
+          ./gradlew build
+
+
       - name: Decompile apk
         run: |
           repo_dir=$(pwd)
